# Generated by Django 3.2.12 on 2023-04-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.CharField(max_length=3000),
        ),
    ]
