# Generated by Django 3.2.12 on 2023-04-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20230410_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='like_coun',
            new_name='like_count',
        ),
    ]
